<?php

namespace Supra\Tests\Validator\Type;

use Supra\Validator\Type\BigIntType;

/**
 * Test class for BigIntType.
 * Generated by PHPUnit on 2011-11-24 at 18:27:56.
 */
class BigIntTypeTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var BigIntType
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new BigIntType;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	public function testValidCases()
	{
		$a = '1';
		$this->object->validate($a);
		self::assertSame('1', $a);
		
		$a = '-1';
		$this->object->validate($a);
		self::assertSame('-1', $a);
		
		$a = '9223372036854775807';
		$this->object->validate($a);
		self::assertSame('9223372036854775807', $a);
		
		$a = '-9223372036854775808';
		$this->object->validate($a);
		self::assertSame('-9223372036854775808', $a);
	}
	
	public function testFailingCases()
	{
		try {
			$a = '9223372036854775808';
			$this->object->validate($a);
			self::fail("Should be invalid");
		} catch (\Supra\Validator\Exception\ValidationFailure $e) {}
		
		try {
			$a = '-9223372036854775809';
			$this->object->validate($a);
			self::fail("Should be invalid");
		} catch (\Supra\Validator\Exception\ValidationFailure $e) {}
		
		try {
			$a = '3a';
			$this->object->validate($a);
			self::fail("Should be invalid");
		} catch (\Supra\Validator\Exception\ValidationFailure $e) {}
		
		try {
			$a = '2e1';
			$this->object->validate($a);
			self::fail("Should be invalid");
		} catch (\Supra\Validator\Exception\ValidationFailure $e) {}
		
		try {
			$a = '19223372036854775808';
			$this->object->validate($a);
			self::fail("Should be invalid");
		} catch (\Supra\Validator\Exception\ValidationFailure $e) {}
	}

}

?>
